services:
  sqnc-node:
    image: digicatapult/sqnc-node:latest
    command: --base-path /data/
      --dev
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 9944:9944
    restart: on-failure
  postgres-data:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    volumes:
      - data-storage:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
volumes:
  data-storage:
