version: '3'

services:
  sqnc-node:
    image: digicatapult/sqnc-node:latest
    command:
      --base-path /data/
      --dev
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure
  postgres-data:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - data-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc
volumes:
  data-storage:
